### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by den-vasyliev** [EvgenPavlyuchek/devsecops#1]
All works good but got:
`sh: line 8: realpath: command not found`

`.git/hooks/pre-commit: line 8: realpath: command not found
Installing pre-commit gitleaks...
Installed pre-commit gitleaks. You can now use it with 'git commit'.
==========================================================================================
Found 0 lines with trailing whitespace.
==========================================================================================
Gitleaks 8.17.0

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

11:51AM INF 0 commits scanned.
11:51AM INF scan completed in 59.4ms
11:51AM INF no leaks found
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean`

**Comment by EvgenPavlyuchek** [comment]
Replaced realpath with readlink. 
script_path="$(realpath "$0")"
script_path="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"

**Comment by YevhenPavliuchek** [comment]
Replaced realpath with readlink.
script_path="$(realpath "$0")"
script_path="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
